const pkm = [ null,
     Bulbasaur = {
           gif: './Assets/Gen1/bulbasaur.gif',
         type1: './Assets/Types/Grass.png',
         type2: './Assets/Types/Poison.png',
            hp: 45,
           atk: 49,
           def: 49,
         spAtk: 65,
         spDef: 65,
           spd: 45},

       Ivysaur = {
           gif: './Assets/Gen1/ivysaur.gif',
         type1: './Assets/Types/grass.png',
         type2: './Assets/Types/poison.png',
            hp: 60,
           atk: 62,
           def: 63,
         spAtk: 80,
         spDef: 80,
           spd: 60},

    Venusaur = {
        gif: './Assets/Gen1/venusaur.gif',
      type1: './Assets/Types/grass.png',
      type2: './Assets/Types/poison.png',
         hp: 80,
        atk: 82,
        def: 83,
      spAtk: 100,
      spDef: 100,
        spd: 80},

    Charmander = {
           gif: './Assets/Gen1/charmander.gif',
         type1: './Assets/Types/fire.png',
            hp: 39,
           atk: 52,
           def: 43,
         spAtk: 60,
         spDef: 50,
           spd: 65},

    Charmeleon = {
           gif: './Assets/Gen1/charmeleon.gif',
         type1: './Assets/Types/fire.png',
            hp: 39,
           atk: 52,
           def: 43,
         spAtk: 60,
         spDef: 50,
           spd: 65},

     Charizard = {
           gif: './Assets/Gen1/charizard.gif',
         type1: './Assets/Types/fire.png',
         type2: './Assets/Types/flying.png',
            hp: 78,
           atk: 84,
           def: 78,
         spAtk: 109,
         spDef: 85,
           spd: 100},

      Squirtle = {
           gif: './Assets/Gen1/squirtle.gif',
         type1: './Assets/Types/water.png',
            hp: 44,
           atk: 48,
           def: 65,
         spAtk: 50,
         spDef: 64,
           spd: 43},

     Wartortle = {
           gif: './Assets/Gen1/wartortle.gif',
         type1: './Assets/Types/water.png',
            hp: 59,
           atk: 63,
           def: 80,
         spAtk: 65,
         spDef: 80,
           spd: 58},

     Blastoise = {
           gif: './Assets/Gen1/blastoise.gif',
         type1: './Assets/Types/water.png',
            hp: 79,
           atk: 83,
           def: 100,
         spAtk: 85,
         spDef: 105,
           spd: 78},

   Caterpie = {
           gif: './Assets/Gen1/caterpie.gif',
         type1: './Assets/Types/bug.png',
            hp: 45,
           atk: 30,
           def: 35,
         spAtk: 20,
         spDef: 20,
           spd: 45},

   Metapod = {
           gif: './Assets/Gen1/metapod.gif',
         type1: './Assets/Types/bug.png',
            hp: 50,
           atk: 20,
           def: 55,
         spAtk: 25,
         spDef: 25,
           spd: 30},

   Butterfree = {
           gif: './Assets/Gen1/butterfree.gif',
         type1: './Assets/Types/bug.png',
         type2: './Assets/Types/flying.png',
            hp: 60,
           atk: 45,
           def: 50,
         spAtk: 90,
         spDef: 80,
           spd: 70},

   Weedle = {
           gif: './Assets/Gen1/weedle.gif',
         type1: './Assets/Types/bug.png',
         type2: './Assets/Types/poison.png',
            hp: 40,
           atk: 35,
           def: 30,
         spAtk: 20,
         spDef: 20,
           spd: 50},

   Kakuna = {
           gif: './Assets/Gen1/kakuna.gif',
         type1: './Assets/Types/bug.png',
         type2: './Assets/Types/poison.png',
            hp: 45,
           atk: 25,
           def: 50,
         spAtk: 25,
         spDef: 25,
           spd: 35},

   Beedrill = {
           gif: './Assets/Gen1/beedrill.gif',
         type1: './Assets/Types/bug.png',
         type2: './Assets/Types/poison.png',
            hp: 65,
           atk: 90,
           def: 40,
         spAtk: 45,
         spDef: 80,
           spd: 75},

  Pidgey = {
           gif: './Assets/Gen1/pidgey.gif',
         type1: './Assets/Types/normal.png',
         type2: './Assets/Types/flying.png',
            hp: 40,
           atk: 45,
           def: 40,
         spAtk: 35,
         spDef: 35,
           spd: 56},

   Pidgeotto = {
           gif: './Assets/Gen1/pidgeotto.gif',
         type1: './Assets/Types/normal.png',
         type2: './Assets/Types/flying.png',
            hp: 63,
           atk: 60,
           def: 55,
         spAtk: 50,
         spDef: 50,
           spd: 71},

  Pidgeot = {
           gif: './Assets/Gen1/pidgeot.gif',
         type1: './Assets/Types/normal.png',
         type2: './Assets/Types/flying.png',
            hp: 83,
           atk: 80,
           def: 75,
         spAtk: 70,
         spDef: 70,
           spd: 101},
]